name: Build and Package macOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.1'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Build and package the app for macOS
      - name: Build and Package
        run: npm run dist

      # Step 5: Upload the built app as an artifact
      - name: Upload macOS Build
        uses: actions/upload-artifact@v3
        with:
          name: macOS-build
          path: dist/
