# Create GitHub Release
- name: Create GitHub Release
  id: create_release
  uses: actions/create-release@v1
  with:
    tag_name: v1.0.0
    release_name: "GRUBA LAW LIBRARY v1.0.0"
    body: |
      🎉 Initial release of the Gruba Law Library app for macOS and Windows!
      Download the `.app` or `.exe` file below.
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Upload macOS Release Asset
- name: Upload macOS Release Asset
  uses: actions/upload-release-asset@v1
  with:
    upload_url: ${{ steps.create_release.outputs.upload_url }}
    asset_path: dist/Gruba-Law-Library-macOS.zip
    asset_name: Gruba-Law-Library-macOS.zip
    asset_content_type: application/zip
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Upload Windows Release Asset
- name: Upload Windows Release Asset
  uses: actions/upload-release-asset@v1
  with:
    upload_url: ${{ steps.create_release.outputs.upload_url }}
    asset_path: dist/Gruba-Law-Library-Windows.zip
    asset_name: Gruba-Law-Library-Windows.zip
    asset_content_type: application/zip
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
