name: GRUBA LAW LIBRARY

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Other steps...

      # Save upload_url into a file
      - name: Save upload_url to file
        run: |
          echo "${{ steps.create_release.outputs.upload_url }}" > upload_url.txt
        shell: bash

      # Save the upload_url as an artifact for use in other jobs
      - name: Save upload_url as artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-info
          path: upload_url.txt

  windows_build:
    runs-on: windows-latest
    needs: build  # Ensure this job runs after the "build" job

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Other steps...

      # Download the release-info artifact from the "build" job
      - name: Download release-info artifact
        uses: actions/download-artifact@v3
        with:
          name: release-info

      # Set the upload_url environment variable
      - name: Set upload_url environment variable
        run: echo "UPLOAD_URL=$(cat upload_url.txt)" >> $GITHUB_ENV

      # Upload Windows .exe Release Asset
      - name: Upload Windows .exe Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ env.UPLOAD_URL }}
          asset_path: dist/Gruba-Law-Library-Windows.zip
          asset_name: Gruba-Law-Library-Windows.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

